version: '2'

services:
  web-demo-api:
    image: stutzlab/multichain-web-demo-api:1.0.0
    build: .
    container_name: multichain-web-demo-api
    ports:
      - 9191:80
    volumes:
      - ./src:/app
